check50:
  checks:
    happy day 1:
      - run: python3 yondu.py
        stdin: |
          20
          1000
        stdout: |
          How many pirates:
          How many units:
          
          Yondu's share: 159.60
          Peter's share: 127.15
          Crew's share: 39.62
        exit: 0
    happy day 2:
      - run: python3 yondu.py
        stdin: |
          35
          100000
        stdout: |
          How many pirates:
          How many units:
          
          Yondu's share: 15197.23
          Peter's share: 11770.63
          Crew's share: 2213.10
        exit: 0
    happy day 3:
      - run: python3 yondu.py
        stdin: |
          49
          39481
        stdout: |
          How many pirates:
          How many units:
          
          Yondu's share: 5735.85
          Peter's share: 4386.49
          Crew's share: 624.65
        exit: 0
      
